// src/lib/components/DurationDisplay.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	let {
		startedAt,
		duration
	}: {
		startedAt: number;
		duration?: number;
	} = $props();

	let elapsedText = $state('0.0s');
	let timerInterval: ReturnType<typeof setInterval> | null = null;

	onMount(() => {
		if (duration != null) {
			elapsedText = `${duration.toFixed(1)}s`;
			return;
		}

		if (!startedAt) {
			elapsedText = '';
			return;
		}

		function tick() {
			const elapsed = (Date.now() - startedAt) / 1000;
			elapsedText = `${elapsed.toFixed(1)}s`;
		}

		tick();
		timerInterval = setInterval(tick, 100);

		return () => {
			if (timerInterval) clearInterval(timerInterval);
		};
	});
</script>

<span class="duration-display">
	{elapsedText}
</span>

<style>
	.duration-display {
		font-variant-numeric: tabular-nums;
		font-size: 11px;
		color: var(--dbx-text-quaternary);
	}
</style>

// src/components/DurationDisplay.tsx
import { useEffect, useRef } from "react";

/** Displays elapsed time with 100ms refresh. */
export function DurationDisplay({
  startedAt,
  duration,
}: {
  startedAt: number;
  duration?: number;
}) {
  const ref = useRef<HTMLSpanElement>(null);

  useEffect(() => {
    if (duration != null) {
      if (ref.current) ref.current.textContent = `${duration.toFixed(1)}s`;
      return;
    }

    // No duration and no valid startedAt -- nothing to display (restored history)
    if (!startedAt) {
      if (ref.current) ref.current.textContent = '';
      return;
    }

    const tick = () => {
      if (ref.current) {
        const elapsed = (Date.now() - startedAt) / 1000;
        ref.current.textContent = `${elapsed.toFixed(1)}s`;
      }
    };
    tick();
    const timer = setInterval(tick, 100);
    return () => clearInterval(timer);
  }, [startedAt, duration]);

  return (
    <span
      ref={ref}
      style={{
        fontVariantNumeric: "tabular-nums",
        fontSize: 11,
        color: "var(--dbx-text-quaternary)",
      }}
    >
      0.0s
    </span>
  );
}
