// src/components/TypingIndicator.tsx
export function TypingIndicator() {
  return (
    <div style={{ display: "flex", alignItems: "center", gap: 4, padding: "4px 0" }}>
      {[0, 1, 2].map((i) => (
        <span
          key={i}
          style={{
            display: "inline-block",
            width: 6,
            height: 6,
            borderRadius: "50%",
            background: "var(--dbx-fill-primary)",
            animation: "bounce 1.4s infinite ease-in-out both",
            animationDelay: `${i * 0.16}s`,
          }}
        />
      ))}
    </div>
  );
}

// src/lib/components/TypingIndicator.svelte
<div class="typing-indicator">
	{#each [0, 1, 2] as i}
		<span
			class="typing-dot"
			style="animation-delay: {i * 0.16}s;"
		></span>
	{/each}
</div>

<style>
	.typing-indicator {
		display: flex;
		align-items: center;
		gap: 4px;
		padding: 4px 0;
	}
	.typing-dot {
		display: inline-block;
		width: 6px;
		height: 6px;
		border-radius: 50%;
		background: var(--dbx-fill-primary);
		animation: bounce 1.4s infinite ease-in-out both;
	}
</style>
